### ISSUE TITLE
terminal native colorschemes?

### ISSUE THREAD

**Issue by wael444** [martanne/vis#1044] opened 2022-10-16 11:29 UTC
currently is it possible to use the terminal's colors (eg. ANSI (`\e[1;31m`)) instead of internal vis colorschemes?

**Comment by ninewise** [comment] 2022-10-16 21:03
Check this thread: https://github.com/martanne/vis/issues/1027

**Comment by mcepl** [comment] 2022-11-10 11:23
@ninewise, isn’t this just a duplicate of #1027? Shouldn’t it be closed as such?

**Comment by wael444** [comment] 2022-11-11 03:42
it still has,,,not been revealed to me how to make a terminal native colorschrme

**Comment by wael444** [comment] 2022-11-11 15:04
> as it's not accessible in the editor

Well, that just means this issue stays open.
Isn't `ESC[X;XXm` possible with colors?

**Comment by ninewise** [comment] 2022-11-12 16:26
Well it is still a duplicate, and the other issue has more info.

**Closed by ninewise** 2022-11-12 16:26 UTC

**Comment by apprehensions** [comment] 2023-02-02 13:36
https://github.com/martanne/vis/blob/1a958f221404b09cb8b0612fb34301e6b9783cf9/ui-terminal-vt100.c#L56-L64

this simply needs to be extended to the other 8 colors; like `32` and `42`, both being normal and high green color.
