### ISSUE TITLE
[ERROR] when exiting from 2 cursors after using the sam's language

### ISSUE THREAD

**Issue by josegl** [martanne/vis#367] opened 2016-08-04 08:12 UTC
In the horizontal splited window where I was editing a javascript file. I had 2 cursors and when I hit the Escape key to leave all the cursors and let just one, this was the error that ocurred:

`/usr/local/share/vis/vis.lua:268: attempt to index a nil value (local 'viewport')`

![screenshot from 2016-08-04 10-04-22](https://cloud.githubusercontent.com/assets/6630934/17394832/793b5416-5a2b-11e6-95d7-75853cee9731.png)

The already splited window, reesplitted again horizontally. 

I was running vis in the following way:

Terminal emulator: st
session manager for terminal emulator: abduco.
Inside abduco dvtm as terminal multiplexer.
5 dvtm windows opened. 3 focused 2 minimized.

I had open the ranger file manager, and the javascript file I was editing was opened from ranger. 

If you need more info about how I reach to the error, please contact me.

**Comment by martanne** [comment] 2016-11-01 15:58
Thanks for the report, can you reliably reproduce the issue? If so, please provide the *minimal* steps required to get the above error. In the meantime c4aaea6 could at least fix the symptoms of the issue. However I'm not sure whether that is enough to recover to a working state ...

**Comment by josegl** [comment] 2016-11-02 07:41
Hi, I've tried to reproduce the issue but I couldn't. I use to get vis synchronized with the master branch, maybe the commit has fixed the problem. I will keep an eye on this.


Thank you :smile:

**Comment by martanne** [comment] 2016-11-09 14:44
The cause was the same as discussed in #408, it should be fixed with the latest commits. Feel free to re-open if you encounter the problem again.

**Closed by martanne** 2016-11-09 14:44 UTC
