### ISSUE TITLE
Support Unicode Combining Characters

### ISSUE THREAD

**Issue by erf** [martanne/vis#117] opened 2015-11-19 15:00 UTC
`æ ø å` characters fails. If cursors is in front, extra space (white square) is added, if before, then two `?`chars are shown.

**Comment by martanne** [comment] 2015-11-19 22:06
I think this is a problem with your fonts (or general system setup) for example the [UTF-8 demo file](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt) works as expected.

**Comment by erf** [comment] 2015-11-19 22:32
Might be, but it works on other text editors. I'm on OSX.

**Comment by twe4ked** [comment] 2015-11-20 04:54
Works here on OS X.

**Comment by erf** [comment] 2015-11-20 10:45
Just to be clear i can see the chars, but there is added extra space to it when cursor is past the char.

**Comment by martanne** [comment] 2015-11-20 11:57
Upon further though the problem is the incorrect handling of [Unicode combining characters](http://unicode.org/faq/char_combmark.html#2). That is `å` can be represented either as `U+00e5` or as `U+030a` (COMBINING RING ABOVE) followed by an `a`. The latter is currently broken. Fixing this is likely non trivial and currently not a priority.

**Comment by greduan** [comment] 2015-11-20 17:03
Thought it'd be relevant to link this here: https://mathiasbynens.be/notes/javascript-unicode

It talks about Unicode in JS and how it could be fixed or handled in your JS app. The solutions probably translate to C so I'm linking it. :)

**Comment by erf** [comment] 2015-11-20 17:12
Whilst we first are posting links.. This is a good article on the subject of unicode http://www.joelonsoftware.com/articles/Unicode.html

**Comment by martanne** [comment] 2015-11-23 13:39
Combining characters of class Nonspacing Mark `Mn` might work now, Enclosing Mark `Me` and Spacing Combining Mark `Mc` will likely still cause problems. They aren't tested and fixing them is definitely not a priority.

Anyway does this cover your use case?

**Comment by erf** [comment] 2015-11-23 16:37
Tested now. I am unfortunately still experiencing problems with `æøå`. If i open them in neovim it looks correct, but "strange things" are happening in `vis` - question marks, white blocks and extra spaces.

**Comment by erf** [comment] 2015-11-23 16:57
Can it be related to ncurses and not having wide version?

**Comment by martanne** [comment] 2015-11-23 17:01
Yes, please provide your test file.

**Comment by erf** [comment] 2015-11-23 17:10
Here is a test file: [no-letters.txt] (https://www.dropbox.com/sh/0s0d5wwojuf03uh/AABpUkwFyWuZYyNqf8OMe5Jua?dl=0)
Problems arises when i move around in the text.

I also get the following warning when i build:
```
~/bin/vis $ make 
cc -D_DARWIN_C_SOURCE -I/usr/include/lua5.1 -I/usr/local/include -I/usr/include/ncursesw -std=c99 -Os -DVERSION="0.r719.g6aa9342" -DNDEBUG -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -DLUA_COMPAT_5_1 -DLUA_COMPAT_5_2 -DLUA_COMPAT_ALL buffer.c libutf.c main.c map.c register.c ring-buffer.c text-motions.c text-objects.c text-regex.c text-util.c text.c ui-curses.c view.c vis-cmds.c vis-modes.c vis-motions.c vis-operators.c vis.c -llua -L/usr/local/lib -ltermkey -lncursesw -lm -ldl -lc -o vis
main.c:1572:15: warning: implicit declaration of function 'wcwidth' is invalid in C99
      [-Wimplicit-function-declaration]
                int width = wcwidth(wc);
                            ^
main.c:1574:10: warning: field precision should have type 'int', but argument has type 'size_t'
      (aka 'unsigned long') [-Wformat]
                        "<%s%.*s> U+%04x ", width == 0 ? " " : "", len, data_cur, wc);
                            ~~^~                                   ~~~
/usr/include/secure/_stdio.h:57:62: note: expanded from macro 'snprintf'
  __builtin___snprintf_chk (str, len, 0, __darwin_obsz(str), __VA_ARGS__)
```

**Comment by erf** [comment] 2015-11-23 17:30
Maybe [this] (https://github.com/hishamhm/htop/issues/301) can help ?

**Comment by martanne** [comment] 2015-11-23 18:21
A couple of comments:

1. the warnings should be fixed
2. your file works here without any problems
3. your file does not contain any combining character sequences. Use `ga` in normal mode to display the Unicode codepoint(s) at the cursor position
4. for example to get an `å` composed of an `a` and a combining character type the following in insert mode: `a`<kbd>Ctrl-v</kbd>`u030a`
5. `wcwidth` seems to be broken on at least some Mac OS X systems (for example gnulib does have a replacement module for it)
6. I do not have time to debug this further, you will have to fix it yourself / find someone familiar with Mac OS X to look into it. I suggest to get a minimal C test case only calling `setlocale` and `wcwidth` to work.
7. Send a patch once you got it working.

**Closed by martanne** 2015-11-23 18:21 UTC

**Comment by erf** [comment] 2015-11-23 18:33
Ok - i'm not sure i will be able to figure this out, but i will look into it when i have time. Maybe you should leave an issue open for this so others might have a go?

**Comment by erf** [comment] 2015-11-23 20:35
Hey, have a look at [this stackoverflow answer](http://stackoverflow.com/questions/3634627/how-to-know-the-preferred-display-width-in-columns-of-unicode-characters/9145712#9145712)
Maybe [wcwidth.c](http://www.cl.cam.ac.uk/~mgk25/ucs/wcwidth.c) is what you need.

**Comment by erf** [comment] 2015-11-23 20:40
Also maybe [this](http://stackoverflow.com/questions/7298059/how-to-count-characters-in-a-unicode-string-in-c?rq=1) if of help.

I will try to set the locale as described  [here](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man3/wcwidth.3.html)

**Comment by erf** [comment] 2015-11-23 21:51
I removed the `LC_ALL=C`from .bash_profile and it worked..

**Comment by andreastt** [comment] 2020-05-03 11:44
I’ve found `æøå` to render correctly when vis is compiled without curses support (`--disable-curses`):

- With `--enable-curses` and `LC_ALL` unset:

      ���

- With `--enable-curses` and `LC_ALL=nb_NO.UTF-8`:

      MMM

- With `--disable-curses` and `LC_ALL` unset:

      ���

- With `--disable-curses` and `LC_ALL=nb_NO.UTF-8`:

      æøå

I’m not an expert on libcurses by any means, but I believe the behaviour with an unset locale is expected. What is surprising is libcurses’ `MMM` rendering of `æøå`.

I hope this helps.
