### ISSUE TITLE
Color is not working in tmux

### ISSUE THREAD

**Issue by hucal** [martanne/vis#621] opened 2017-10-16 18:40 UTC
Vis is not rendering colors correctly when I run it in tmux.

Here is a demo where I run vis in tmux using several terminal emulators (stterm, lxterminal, and the xfce4 terminal). The bottom-left shows vis running without tmux.

![](https://i.imgur.com/BuM3TYf.png)

I have this line in my tmux config: `set -g default-terminal "xterm-256color"`.
Vis behaves the same when using the `light-16` and `default-256` themes.
Vim and Neovim work fine with or without tmux.

**Comment by hucal** [comment] 2017-10-16 18:43
I also encounter the same problem as in #611, except it's not just the background color.

**Comment by wgrriffel** [comment] 2017-10-18 21:19
@hucal what if instead tmux configs you try this in your shell:
TERM="screen-256color"
export TERM

**Comment by hucal** [comment] 2017-10-18 23:11
That works. I still need to test this on other systems.

**Comment by mqudsi** [comment] 2017-11-03 17:53
I have no problem with colors under tmux, but I'm using the latest version of tmux compiled against ncurses 6.0, which adds `tmux-256color` to the valid `TERM` configurations. This is the (only) correct `TERM` value for tmux sessions.

![image](https://user-images.githubusercontent.com/606923/32388476-cca7c248-c095-11e7-9ac3-8c1b32752af5.png)

**Comment by mqudsi** [comment] 2017-11-03 17:54
Oh, and the correct way to set the `TERM` value in the `.tmux.conf` file is with 

```
set -g default-terminal "tmux-256color" #or whatever other value you deem correct
```

**Comment by martanne** [comment] 2017-11-04 14:35
I'm not 100% sure what the current status with tmux is, but what @mqudsi mentions sounds about right.

I believe back in January a vis user (@s-gilles) enhanced tmux to [support the required terminal escape sequences](https://github.com/tmux/tmux/pull/710).

I'm going to close this for now, make sure to retry with the latest version of all involved components and reopen if the issue persists.

**Closed by martanne** 2017-11-04 14:35 UTC
Labels: terminal

**Comment by hucal** [comment] 2017-11-06 16:18
I pulled and compiled the latest version of tmux and `vis` works perfectly now. I can confirm that I only need the following line in `.tmux.conf`:

```
set -g default-terminal "tmux-256color"
```

Thank you!

**Comment by HalosGhost** [comment] 2018-02-01 19:15
using vis-git, and ncurses 6.1-3 (on archlinux), I am having this issue again.

Below is my `.tmux.conf`:

```
set-option -g default-terminal "tmux-256color"
set-option -g set-titles on
set-option -g escape-time 10
set-option -g set-titles-string "#{pane_current_command}"
set-option -g status "on"
set-option -g status-position "top"
set-option -g status-right ""
set-option -g status-left "#[fg=brightblue]#[bg=black]"

set-option -g status-style "fg=brightblue,bg=black"
set-option -g window-status-separator ""
set-option -g window-status-format "#{?window_index,,}#{?window_bell_flag,#[fg=green],#[fg=white]} #W "
set-option -g window-status-current-format "#{?window_index,,} #W "
set-option -g window-status-bell-style ""

bind -n S-down new-window
bind -n S-left prev
bind -n S-right next
bind -n C-left swap-window -t -1
bind -n C-right swap-window -t +1

unbind -n C-space
bind -n C-space run-shell -b turl
unbind -n C-y
bind -n C-y run-shell -b "turl -g"
```

And under a shell in tmux with this config, I do see ``TERM=tmux-256color``

Thoughts?

**Comment by HalosGhost** [comment] 2018-02-19 17:11
As of the latest branch merge (https://github.com/martanne/vis/commit/70dd3140bbb664bba5852c0c3fe6bae92c484f7b), all is working lovely now.

Thank you!

**Comment by hyiltiz** [comment] 2020-02-11 02:24
The background color was green in `vis v0.5 Jan 14, 2017 (shipped with Debian testing)` in `Konsole 19.08.1` where `echo $TERM` produced `xterm-256color`. 

- About `xterm-256color`:  Calling `TERM='xterm-256color' vis` in `xfce4-term`, `alacritty`, `kitty`, `xterm`, `tmux`, `screen` worked without issues. 
- About `konsole`: Calling `TERM='xterm' vis`, `TERM='xterm-16color' vis`, `TERM='screen-256color' vis` in `Konsole` fixed the blue background.

**Comment by ddkn** [comment] 2021-12-26 21:46
Just thought I would update that this is still an issue on *Debian Bullseye* using `konsole` with `vis=0.7-2`, see below

```
$ uname -srvo
Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) GNU/Linux
```

![image](https://user-images.githubusercontent.com/13819239/147420602-669c48fe-3f5a-482b-b940-d910ef6692b5.png)

![image](https://user-images.githubusercontent.com/13819239/147420622-970e2d7a-4b93-494b-a7e5-1123f0950562.png)

![image](https://user-images.githubusercontent.com/13819239/147420625-e4e126ef-82d7-46c0-ac0c-65625210f56c.png)

But in `tmux` within `konsole` works just fine,

![image](https://user-images.githubusercontent.com/13819239/147420645-a95deb92-7e63-4398-8dd7-a6096e9a24ba.png)

As @hyiltiz said, works fine when you use `TERM='xterm' vis` or `TERM='tmux-256color' vis` in `konsole`

**Comment by hyiltiz** [comment] 2021-12-26 22:38
I reported this issue with KDE Konsole as well, but I think this is an issue for Vis.

**Comment by cideM** [comment] 2023-10-27 12:38
With 

```shell
$ echo $TERM
tmux-256color
```

`vis` does not render colors correctly for me in Alacritty when using tmux. It works with `TERM='xterm-256color' vis` though.

**Comment by rnpnr** [comment] 2023-10-27 13:55
If running `TERM='xterm-256color vis` gets vis working with colors inside tmux then the issue is with the `tmux-256color` terminfo entry or your terminal editor. I'm inclined to believe the latter since vis works inside tmux with colors on both Gentoo (default term inside tmux `TERM=screen-256color`) and Arch (`TERM=tmux-256color`) with  `st` as the terminal emulator.

I'm locking this so that people aren't getting pinged with comments from a 6+ year old issue that's not even ours.
