### ISSUE TITLE
Release to enable vis to be packaged

### ISSUE THREAD

**Issue by radare** [martanne/vis#78] opened 2015-10-12 11:46 UTC
Related to https://github.com/voidlinux/void-packages/issues/2434

**Comment by pullmoll** [comment] 2015-10-15 09:02
I second that. A release tag and archive would be fine and I would package `vis` for Void Linux ASAP.

**Comment by martanne** [comment] 2015-10-15 22:16
I don't really understand why a git snapshot can't be packaged, but if there is demand for it I can tag a release. Ideally I would have liked to fix few more bugs (e.g. #70 and #44). 

Also I'm experimenting with a lua based syntax highlighting code. If we conclude that integrating lua is a sensible thing to do, then this will likely lead to some architectural changes. Cutting a release before breaking everything might not be such a bad idea.

For any user out there, it would be nice if you could give current git HEAD a try and report whether you encountered any show stopper bugs which have to be fixed before cutting a release. I'm tagging a few people who contributed patches/feedback in the past. @erf @eworm-de @jvoisin @rpmohn @rychipman @TieDyedDevil @trengrj

**Comment by pullmoll** [comment] 2015-10-15 23:07
IMHO tagging is nothing to be considered an ultimate point in time where accusations could be primed upon. Tagging is more of a convenience for packagers who love to deal with something shorter than a snapshot's hash :)

As the one who develops this package, you are most probably the most knowing person to tell when some kind of (may it be minor) stage is achieved. A git snapshot is just a tad more arbitrary and a packager picking it up may just slightly miss the *sweet spot*, because he doesn't follow every internal ongoing discussion for the package.

Or the other way round: the more releases you tag, the finer grained reports on how good or bad your application works for the unknowing user *may* be generated by rolling release distributions like Void Linux.

**Comment by TieDyedDevil** [comment] 2015-10-16 01:39
I use vis as my only screen-based editor (i.e. not ed or sed) on all three of my Fedora machines and have been keeping up with HEAD on an almost daily basis. I am not aware, at the moment, of any show stoppers.

On Thu, Oct 15, 2015 at 03:16:55PM -0700, Marc André Tanner wrote:
>    I don't really understand why a git snapshot can't be packaged, but if
>    there is demand for it I can tag a release. Ideally I would have liked
>    to fix few more bugs (e.g. [1]#70 and [2]#44).
> 
>    Also I'm experimenting with a lua based syntax highlighting code. If we
>    conclude that integrating lua is a sensible thing to do, then this will
>    likely lead to some architectural changes. Cutting a release before
>    breaking everything might not be such a bad idea.
> 
>    For any user out there, it would be nice if you could give current git
>    HEAD a try and report whether you encountered any show stopper bugs
>    which have to be fixed before cutting a release. I'm tagging a few
>    people who contributed patches/feedback in the past. [3]@erf
>    [4]@eworm-de [5]@jvoisin [6]@rpmohn [7]@rychipman [8]@TieDyedDevil
>    [9]@trengrj
> 
>    —
>    Reply to this email directly or [10]view it on GitHub.
> 
> References
> 
>    1. https://github.com/martanne/vis/issues/70
>    2. https://github.com/martanne/vis/issues/44
>    3. https://github.com/erf
>    4. https://github.com/eworm-de
>    5. https://github.com/jvoisin
>    6. https://github.com/rpmohn
>    7. https://github.com/rychipman
>    8. https://github.com/TieDyedDevil
>    9. https://github.com/trengrj
>   10. https://github.com/martanne/vis/issues/78#issuecomment-148538836

-- 
The system will collapse if we refuse to buy what they are selling --
their ideas, their version of history, their wars, their weapons, their
notion of inevitability.

Remember this: We be many and they be few. They need us more than we
need them.

Another world is not only possible, she is on her way. On a quiet day,
I can hear her breathing.

  -- Arundhati Roy

**Comment by eworm-de** [comment] 2015-10-16 07:56
From a technical point of view it is not a problem to package from git with just a hash. Packagers do like tags, however: A tag intends that the developer expects this state to be stable. And it stops users from asking to update the package to latest hash / HEAD. ;)

I would like to see a better colour theme for syntax highlighting on dark background. That is not a show stopper, though.

BTW, I would like to package vis for Arch Linux. Currently it's just in AUR. Go and give your vote:
https://aur.archlinux.org/packages/vis/

**Comment by martanne** [comment] 2015-10-18 21:44
> I would like to see a better colour theme for syntax highlighting on dark background.

I pushed my work in progress of the lua based syntax highlighting code to a [new branch](https://github.com/martanne/vis/tree/lua/) take a look at `lexers/themes` directory if you want to play around with it.

**Comment by martanne** [comment] 2015-11-09 17:04
By now I've done some long due refactorings, fixed a few bugs and merged the lua based syntax highlighting code. Those of you interested in a release should update to current master and report any issues they encounter.

**Comment by radare** [comment] 2015-11-20 03:03
is LUA a mandatory dependency?

**Comment by martanne** [comment] 2015-11-20 15:03
Yes.

At the moment it is only used for syntax highlighting, so should be relatively easy to rip out if you wish to do so. However I would like to avoid compile time feature selection and the resulting `#ifdef` mess. Also I suspect that Lua usage will increase in the future (at first mainly for configuration, but later maybe also to extend core editor functionality).

Among the things I considered, the PEG based approach to syntax highlighting using Lua/LPeg seems to suck the least.

**Comment by radare** [comment] 2015-11-20 18:43
Yes i would prefer to be able to have small vis builds without lua or any external dependency if possible. But i understand a scripting language is gonna be useful for future use cases

**Comment by radare** [comment] 2015-12-22 11:24
I was happy with vis being dependant only on ncurses, now it needs termkey and lua, which are not really heavy dependencies, but it will be good to add some build options to get rid of them if possible just to embed vis on routers and other low-memory devices.

Anyway, feel free to release when you want. I would be happy to package and test it more.

Thanks!

**Comment by martanne** [comment] 2015-12-23 13:21
I agree that vis should strive to be usable on low memory devices. I'm currently investigating ways to expose some of vis's functionality as a Lua API (turns out this is not completely trivial due to object lifetime issues between C/Lua). As this might require some structural changes I would like to get the basic infrastructure in place before a release. While doing so I will try to come up with a reasonable way of making Lua support optional.

As for libtermkey, it is only 4 C files resulting in a ~40K library which I'm quite happy to pay in order to get rid of the headache that is terminal input handling.

**Comment by radare** [comment] 2015-12-23 18:57
It's sad that libtermkey doesnt comes in ncurses, but well.. ncurses is
a big pile of legacy crap, but it comes in base system of almost every
single OS... 40KB of code looks likes a lot to me, but anyway, i know
what's handling terminal input and i guess that's a necessary thing.

+1 to make lua dependency optional

--pancake

**Comment by martanne** [comment] 2015-12-26 21:20
> ncurses is a big pile of legacy crap

I agree, however it gets the job done and as you noted it is available on most systems.

> 40KB of code looks likes a lot to me

I haven't actually looked at the code, but instead use it as a black box.
In general vis is currently not really optimized for size. For example the help texts are included in the binary, some structs contain various pointers instead of an union etc. The goal is to build a simple, yet efficient vim like editor. The relative small binary size is more of a by-product.

> +1 to make lua dependency optional

Try `make CONFIG_LUA=0` you will lose syntax highlighting (and yes the build system is a bit of a mess).

As there are no architectural changes planned for the near future, getting some testing feedback and tagging a release would make sense ...

**Comment by martanne** [comment] 2015-12-30 09:05
I intend to do a release later on today/tomorrow. Hence if there are some changes needed from a package maintainers (@eworm-de, @pullmoll?) point of view, now would be a good time to mention them ...

**Comment by pullmoll** [comment] 2015-12-30 13:39
Nothing special from me. I believe it will be easy to package for Void.

**Comment by eworm-de** [comment] 2015-12-30 18:14
I did not test last commits, but there are no show-stoppers I know of.

**Comment by martanne** [comment] 2016-01-01 16:28
It finally [happened](http://lists.suckless.org/dev/1512/28045.html).

**Closed by martanne** 2016-01-01 16:28 UTC

**Comment by radare** [comment] 2016-01-01 18:41
👏

**Comment by erf** [comment] 2016-01-01 19:34
👏👌

**Comment by martanne** [comment] 2016-02-12 16:10
Enough changes/bugfixes/improvements have been accumulated to warrant another release. Hence if somebody feels like doing some basic testing, now would be a good time to do so ...

**Comment by TieDyedDevil** [comment] 2016-02-12 17:14
I use vis daily on three Fedora 23 machines; vis is my only editor. From that perspective, I'm giving it a pretty good workout. I've haven't encountered anything that'd block a release.

If I have time this weekend I'll grovel the git log for specific areas that might warrant more attention. Meanwhile, I'd be happy to test any specific areas you name.

**Comment by martanne** [comment] 2016-02-12 19:37
Thanks, the new prompt history is probably the most "user facing" change.

In general building up a [test suite](https://github.com/martanne/vis/tree/test/test/vim) would be highly appreciated. I realize this is probably not the most interesting thing to work on, but it would be extremely useful to catch regressions in the future. Also you probably know more about shell scripting than I do, so feel free to completely rewrite it if you feel there is a better way to implement it.

In general if somebody has no C knowledge or doesn't wan't to spend time delving into the code base (though I hope this relatively easy, after all a goal of vis is to be hackable) but still would like to contribute to the project, extending the test suite is a good opportunity to do so.

As this is simple black box testing i.e. feeding the editor some input and checking that it does the right thing, one might also learn a few obscure vim features along the way. For example testing some *simple* vimgolf entries might be interesting ...

**Comment by erf** [comment] 2016-02-13 19:50
I have been testing most of the functionality in vis now and it seems to work great. I found a little anoyance reported in #164 . Will look into creating some tests when i have time.

**Comment by martanne** [comment] 2016-02-18 16:42
An annoying thing I noticed is that in some cases the implicit macro recording for the dot command does not stop at the right time, causing breakage when a command is repeated with `.`

**Comment by martanne** [comment] 2016-03-25 08:51
[vis version 0.2 is out](http://lists.suckless.org/dev/1603/28590.html)

**Comment by radare** [comment] 2016-03-25 09:28
thanks! i'm pushing to get it packaged in voidlinux

On 25 March 2016 at 09:51, Marc André Tanner <notifications@github.com>
wrote:

> vis version 0.2 is out <http://lists.suckless.org/dev/1603/28590.html>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/martanne/vis/issues/78#issuecomment-201205323>
>



-- 
--pancake
