### ISSUE TITLE
libtermkey is deprecated

### ISSUE THREAD

**Issue by nabeelomer** [martanne/vis#244] opened 2016-04-09 11:07 UTC
The [webpage](http://www.leonerd.org.uk/code/libtermkey/) says:

> Note: This project is now DEAD; end-of-life. There will likely be no further releases.

> All of the code will be migrated into libtickit instead. libtermkey should not be used for new programs; use libtickit.

**Comment by aeosynth** [comment] 2016-04-09 23:09
dupe of #79 

> Because it works and I have zero interest in dealing with the mess that is low level terminal input handling. Besides it consists of only 3 C files which could always be included in vis directly (but I prefer not to do so).

**Closed** 2016-04-10 04:39 UTC
