### ISSUE TITLE
ctags support or any better solution

### ISSUE THREAD

**Issue by realwhz** [martanne/vis#547] opened 2017-05-12 19:24 UTC
Hi all,

First of all, I am very glad to find this project.  I am long time vim user and also have experience of sam and acme when I used plan9 many years ago.

It seems that tags based code navigation is not supported.  Since it is very useful feature when studying C codes (or even C++ codes), I wondered if there is any plan to do so?  Or if there are better solutions than ctags, could you please share them?  I browsed the issues list but didn't find discussion.  Please forgive me if I missed the discussion and raised a duplicated issue.

Thanks.

**Comment by josuah** [comment] 2017-05-12 19:33
> Or if there are better solutions than ctags, could you please share them?

I do not know ctags very well: they are a map between syntaxic elements and position in the code ?  If so, I think the lua API permit to put the cursor anywhere in the code.

One might be able to implement a shell or lua script that parse the ctags, read something from.the keyboard, then calls the lua API to put the cursor at the right position.

**Comment by realwhz** [comment] 2017-05-12 19:48
Hi josuah,

Yes, ctags is a standalone utility generating a tags file which is a map between tokens/names and positions in the code.  vim has built-in support of ctags: when instructed, vim will parse the tags file and jump to the corresponding location; vim also maintains a stack of jumping positions so that it can navigate back and force even across files.

What your said sounds technically feasible.  Just one more newbie question, can user bind keys to certain functionality in vis?  I meant if it is configurable to use for example <C-]> and <C-t> for these tasks.

Thanks.

**Comment by martanne** [comment] 2017-05-12 20:10
Yes the functionality will eventually be supported. I'm not yet sure about exact technical details.

Using ctags is certainly a possibility. Another option might be the [Language Server Protocol (LSP)](http://langserver.org/), it is more complex but should allow more advanced functionality. In an ideal world the structural regex based language would be "lifted" to understand the language semantics. I.e. something like `:x@foo@c/bar` (not sure about the exact syntax nor whether the protocol provides the necessary primitives) would rename the *variable* `foo` to `bar`.

I might be able to work on some of these ideas during the upcoming summer.

As for user mappings, you can bind  [arbitrary Lua functions to keys](http://martanne.github.io/vis/doc/#Vis:map). However, at this point the event loop is not exposed to Lua, meaning the editor core is blocked while Lua code is running.

**Comment by Shugyousha** [comment] 2017-05-12 20:56
On Fri, May 12, 2017 at 01:10:56PM -0700, Marc André Tanner wrote:
> Yes the functionality will eventually be supported. I'm not yet sure
> about exact technical details.

I am interested in this functionality as well.


> Using ctags is certainly a possibility. Another option might be the
> [Language Server Protocol (LSP)](http://langserver.org/), it is
> more complex but should allow more advanced functionality. In an

I looked at the LSP project a little bit and it seems like they suggest
having a server speaking the LSP protocol. The advantage of this would
be that vis would get support for all languages that already have LSP
servers available.

Would you prefer having the communication with such a server implemented
in C or in lua?


> ideal world the structural regex based language would be "lifted" to
> understand the language semantics. I.e. something like `:x@foo@c/bar`
> (not sure about the exact syntax nor whether the protocol provides the
> necessary primitives) would rename the *variable* `foo` to `bar`.

I assume that the "Find References Request"[0] could be used for this.


Cheers,

Silvan

[0] https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_references

**Comment by kupospelov** [comment] 2017-05-23 21:22
Hi, I think using a ctags plugin is an option at least for now, so I've created [one](https://github.com/kupospelov/vis-ctags) to provide some basic ctags support. Generally, it seems to work fine most of the time, however there are several limitations:
- The tags file should be generated with the `-n` option, so that it only contains line numbers.
- The result is shown in a new window.

I have not checked how it is implemented in vim, but noticed that in some cases vim navigates to a different location. However when I found this out both the plugin and vim were wrong, so I'm not sure if this is an issue. The implementation is as simple as possible, handling of some cases may definitely be improved.

**Comment by realwhz** [comment] 2017-05-23 21:56
Thanks kupospelov!  I will try your work.  Currently I use universal ctags' readtag cmd to return the position of searched tag instead of parsing the tags file.  What vim does I believe is to have some additional check if there are multiple matches.

**Comment by Shugyousha** [comment] 2017-05-24 07:18
Hi Konstantin

On Tue, May 23, 2017 at 11:22 PM, Konstantin Pospelov
<notifications@github.com> wrote:
> Hi, I think using a ctags plugin is an option at least for now, so I've
> created one to provide some basic ctags support. Generally, it seems to work
> fine most of the time, however there are several limitations:
>
> The tags file should be generated with the -n option, so that it only
> contains line numbers.
> The result is shown in a new window.

Sounds interesting, at least as a first version! I will try it out.

If the search using unversal ctags' readtag command that Hongzheng
mentioned works better, maybe we should use the "readtag" binary by
default?


Cheers,

Silvan

**Comment by realwhz** [comment] 2017-05-24 16:59
Hi kupospelov and all,

I modified your script to use readtags.  It can be found at [here](https://github.com/realwhz/vis-plugins/blob/master/ctags.lua)

The plugin now supports normal ctags' tags file; no need to use "-n" to regenerate.  It has two keybindings: C-] to jump to the match and g C-] list all matches.

I am not very familiar with lua.  So please feel free to correct it.

P.S. there is also a plugin using ag to list all matches under cursor [here](https://github.com/realwhz/vis-plugins/blob/master/ag.lua)

Thanks a lot.

**Comment by kupospelov** [comment] 2017-05-24 20:41
Frankly, I have not used universal ctags before, it is not even in the Archlinux repositories, so I've built it from AUR. From what I can see, the choice is not obvious.
The Lua implementation actually does the same thing. There is no issue with search in the tags file, the challenge here is to determine which match to use in case there are several ones. From this perspective readtag is no better - it just returns all the matches so we again have to deal with this ourselves.
I also tested both readtag and the Lua implementation (as a separate lua script) on the Linux kernel tags file (282MB) and surprisingly readtags took longer to find the same word (0.345s vs 0.006s). I can only guess why it was so (different buffer size? the fact that I used SSD?).
I definitely agree that it's useful to be able to see all matches and search by pattern is really great. However for now I lean towards staying with the Lua search just because it doesn't require an external tool to be installed, it is fast enough, and at this point switching to readtags doesn't seem to bring much value until it doesn't work faster on huge tags files (at least on my computer it does not).
Thanks.

**Comment by Shugyousha** [comment] 2017-05-25 16:37
On Wed, May 24, 2017 at 01:41:51PM -0700, Konstantin Pospelov wrote:
> The Lua implementation actually does the same thing. There is no issue
> with search in the tags file, the challenge here is to determine which
> match to use in case there are several ones. From this perspective
> readtag is no better - it just returns all the matches so we again
> have to deal with this ourselves.  I also tested both readtag and the

I would argue that having an external program do the search means that
we don't have to do it ourselves. This has the additional advantage of
less code (and thus potentially fewer bugs) being in vis which is
always nice.


> Lua implementation (as a separate lua script) on the Linux kernel tags
> file (282MB) and surprisingly readtags took longer to find the same
> word (0.345s vs 0.006s). I can only guess why it was so (different

That is a surprising result!

I tried the kernel ctag file with 'readtags' on my old HDD and got around
0.38 to 0.4 seconds as well. I would have expected the search to be
faster but it's not too bad in any case (since most projects won't have
a 316MB tags file like the current kernel seems to have).


> buffer size? the fact that I used SSD?).  I definitely agree that it's
> useful to be able to see all matches and search by pattern is really
> great. However for now I lean towards staying with the Lua search just
> because it doesn't require an external tool to be installed, it is

Well, it still needs ctags (the non-universal one) installed... or
another program that generates the same file format.


> fast enough, and at this point switching to readtags doesn't seem to
> bring much value until it doesn't work faster on huge tags files (at
> least on my computer it does not).

Actually, your script did not work for a tag file created with (universal)
ctags and the -n option. If I use the mapped key combination on an
'absolute_path' call in vis.c, a new empty window for a non-existing file
named 's.c' opens. I assume that the file name and/or the line number
do not get parsed correctly but I have not looked into it more closely.

I also tried out the readtags version. This one seems to work for me
when using the -n flag to build the tags file with universal ctags.

The universal ctags version also has the advantage of working with more
programming languages (about 95 of them according to the documentation).

As long as one of the versions work, I am quite happy already! The
missing ctags functionality is one of the things that has prevented me
from using vis as my daily driver to write code. At one point we should
also look into having a tag stack if martanne is not against having one.

Thanks for all the work!

**Comment by kupospelov** [comment] 2017-05-25 20:00
> I would argue that having an external program do the search means that
we don't have to do it ourselves. This has the additional advantage of
less code (and thus potentially fewer bugs) being in vis which is
always nice.

I agree, it's generally better not to reinvent the wheel and reuse solutions that already exist. However what I really meant is that readtags does not resolve which exactly match we should use, it just returns all the matches. You can try it yourself by running `readtags vis` in the vis directory - I get 7 matches for this query. What it actually replaces is about 50 lines of code which are not too complex.

> I tried the kernel ctag file with 'readtags' on my old HDD and got around
0.38 to 0.4 seconds as well.

I would expect it to run slower on an HDD. However when I run the test I used a tag in the top of the file, so that it would require several search iterations, something like this:
```
$ time readtags -t tags AC97_CXR_SPDIF_AC3
AC97_CXR_SPDIF_AC3  ./include/sound/ac97_codec.h    314

real    0m0.378s
user    0m0.321s
sys 0m0.057s
```
May be that's the cause.

> Actually, your script did not work for a tag file created with (universal)
ctags and the -n option. If I use the mapped key combination on an
'absolute_path' call in vis.c, a new empty window for a non-existing file
named 's.c' opens.

I can't reproduce it. From the description it seems that the tag was actually found in vis.c, but since the script expects all the filenames to begin with ./, it removes the first two characters. I have managed to create such file with the `--tag-relative=yes` option, maybe it's turned on by default in your universal ctags version. The readtags version does not try building the full path and works with relative one, that's why it works in this case, I guess.

Obviously both approaches have pros and cons. Generally, I look forward to using universal ctags for this purpose, but it seems that it's still in active development and has not yet replaced ctags. The very fact that it has to be built from sources while ctags is available in the repo may be inconvenient for some users. The pure Lua solution works fine with standard ctags, but obviously may fail when it encounter something unexpected in the tags file.

Anyway, I'm glad that what we did here turned out to be useful.

**Comment by realwhz** [comment] 2017-05-25 21:28
Regarding multiple matches issue, here is my two cents.

It is just impractical to attempt to get the single "best" match from ctags results.  ctags is not compiler and won't be able to generate tags file that has no ambiguities for all tags.  For example, C/C++ has conditional compilation, and ctags won't know which tag is the final one without consulting compilation settings.

In this sense, I think it is good for the tool to list all relevant matches instead of choose one for us.  vim actually uses this approach; with proper config, vim will list all matches if there are more.  The only difference is that vim has the capability to browse all the matches easily.

As for Universal Ctags, although it is still actively developed, it is mature enough.  It is actually the successor of Exuberant Ctags.  readtags takes care of a lot of corner cases in parsing tags file.  It is not just a binary search in tags file.

**Comment by Shugyousha** [comment] 2017-05-26 07:02
On Thu, May 25, 2017 at 10:00 PM, Konstantin Pospelov
<notifications@github.com> wrote:
>> I tried the kernel ctag file with 'readtags' on my old HDD and got around
>> 0.38 to 0.4 seconds as well.
>
> I would expect it to run slower on an HDD. However when I run the test I
> used a tag in the top of the file, so that it would require several search
> iterations, something like this:
>
> $ time readtags -t tags AC97_CXR_SPDIF_AC3
> AC97_CXR_SPDIF_AC3  ./include/sound/ac97_codec.h    314
>
> real    0m0.378s
> user    0m0.321s
> sys 0m0.057s
>
> May be that's the cause.

After reading the file once it should be in the page cache. From that
point on the speed of the harddisk shouldn't matter anymore.


>> Actually, your script did not work for a tag file created with (universal)
>> ctags and the -n option. If I use the mapped key combination on an
>> 'absolute_path' call in vis.c, a new empty window for a non-existing file
>> named 's.c' opens.
>
> I can't reproduce it. From the description it seems that the tag was
> actually found in vis.c, but since the script expects all the filenames to
> begin with ./, it removes the first two characters. I have managed to create
> such file with the --tag-relative=yes option, maybe it's turned on by
> default in your universal ctags version. The readtags version does not try
> building the full path and works with relative one, that's why it works in
> this case, I guess.

Hm, if I find the time I will look into it.

**Comment by Shugyousha** [comment] 2017-05-26 07:07
On Thu, May 25, 2017 at 11:28 PM, Hongzheng Wang
<notifications@github.com> wrote:
> Regarding multiple matches issue, here is my two cents.
>
> It is just impractical to attempt to get the single "best" match from ctags
> results. ctags is not compiler and won't be able to generate tags file that
> has no ambiguities for all tags. For example, C/C++ has conditional
> compilation, and ctags won't know which tag is the final one without
> consulting compilation settings.
>
> In this sense, I think it is good for the tool to list all relevant matches
> instead of choose one for us. vim actually uses this approach; with proper
> config, vim will list all matches if there are more. The only difference is
> that vim has the capability to browse all the matches easily.

Yes, showing all the options is definitely desirable. How to best
handle the choice of these options in vis is still an open question.


> As for Universal Ctags, although it is still actively developed, it is
> mature enough. It is actually the successor of Exuberant Ctags. readtags
> takes care of a lot of corner cases in parsing tags file. It is not just a
> binary search in tags file.

That's why I also think using readtags is probably the more robust and
simpler way to get the right match(es) and thus a better tag browsing
functionality in vis.

**Comment by Shugyousha** [comment] 2017-05-28 15:07
On Thu, May 25, 2017 at 01:00:54PM -0700, Konstantin Pospelov wrote:
>> Actually, your script did not work for a tag file created with (universal)
> ctags and the -n option. If I use the mapped key combination on an
> 'absolute_path' call in vis.c, a new empty window for a non-existing file
> named 's.c' opens.
> 
> I can't reproduce it. From the description it seems that the tag was
> actually found in vis.c, but since the script expects all the filenames
> to begin with ./, it removes the first two characters. I have managed to
> create such file with the `--tag-relative=yes` option, maybe it's turned
> on by default in your universal ctags version. The readtags version does
> not try building the full path and works with relative one, that's why
> it works in this case, I guess.

Probably not relevant anymore but I tracked down what the issue was. In
the 'search' function there was the following line:

local fullpath = prefix .. value.filename:sub(3)

and when I removed the :sub(3) everything worked.

I cannot find this line in the current version of the script online so
maybe I downloaded an old version by mistake? Not sure.


Cheers,

Silvan

**Comment by kupospelov** [comment] 2017-06-03 18:37
>I cannot find this line in the current version of the script online so
maybe I downloaded an old version by mistake? Not sure.

I think the answer is that I updated the script just the day before your last comment was posted. :)

By the way, last time I added support for multiple matches, so now it should be easy to choose the right one.

Since a filename may or may not be preceded with './', I'll add handling for this when I have a bit of spare time.

**Comment by mqudsi** [comment] 2017-09-18 19:49
Note that ctags support can be implemented via a language server, then there would be no need for multiple interfaces.

**Comment by Shugyousha** [comment] 2017-09-19 07:44
On Mon, Sep 18, 2017 at 9:49 PM, Mahmoud Al-Qudsi
<notifications@github.com> wrote:
> Note that ctags support can be implemented via a language server, then there
> would be no need for multiple interfaces.

The ctags file format is an interface as well. As long as you your
editor can read ctag files (and you have a "ctagger" for your
language) the editor supports jumping to function definitions (and
other things). I am quite sure that the language server format allows
you to support more features than the ctag file format though (at
least it should since it seems to be a lot more complex).


Cheers,

Silvan

**Comment by deepcube** [comment] 2018-04-30 21:51
I wrote a patch that opens the tag in the same window and keeps a tag stack so you can return to previous positions with <C-t> like in vim. I created a pull request but I don't know if it will (or should) be accepted. Just wanted other people to know about the option.

https://github.com/deepcube/vis-ctags/commit/a036c70acc11a2f5761419edc6bb0a0015c537a7

**Comment by seifferth** [comment] 2019-10-11 12:05
I'm actually using the plugin a lot and it works great. I guess this issue could be closed, as the plugin actually solves the problem.

**Comment by martanne** [comment] 2020-02-04 17:55
Ok, I'm closing this because the functionality seems to be provided by the [vis-ctags plugin](https://github.com/kupospelov/vis-ctags).

Integrating LSP functionality is still a worthwhile goal, but will likely require a few architectural changes.

**Closed by martanne** 2020-02-04 17:55 UTC

**Comment by mcepl** [comment] 2020-03-16 21:28
> Using ctags is certainly a possibility. Another option might be the [Language Server Protocol (LSP)](http://langserver.org/), it is more complex but should allow more advanced functionality.

Just +100 to LSP. I believe that it is the future, and supporting anything else (including ctags) is wee bit waste of time. Also, LSP client for neovim (https://github.com/neovim/neovim/tree/master/runtime/lua/vim/lsp.lua and subdirectory ``lua/``) is all written in Lua. Of course, it is not directly portable, but it might be a good ground work for it.
