### ISSUE TITLE
Double quotes are incorrectly matched sometimes

### ISSUE THREAD

**Issue by Vintodrimmer** [martanne/vis#711] opened 2018-06-08 18:16 UTC
Good day,

As you can see in the screenshot, wrong quotes are highlighted. If I select previous or next quotation mark, the match will be correct. Is this intended behaviour?

![screenshot](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2018-06-08-20%3A10%3A34-screenshot.png)

**Comment by PuercoPop** [comment] 2018-06-09 02:03
@Vintodrimmer Could you share the file in a gist? Can't reproduce locally

**Comment by Vintodrimmer** [comment] 2018-06-09 08:20
@PuercoPop I don't have that particular config anymore, but [this one](https://gist.github.com/Vintodrimmer/6037ce50fde71b49c40b5b700f39b649) shows the same issue when you select the second quote on the 6th line.
The issue is present when run as root, that has a default visrc.lua. 
![screenshot](https://raw.githubusercontent.com/Vintodrimmer/docs/master/2018-06-09-10%3A17%3A24-screenshot.png)

**Comment by 5jqk2ymwqd** [comment] 2018-06-12 17:29
In my limited testing this happens with tabs but not with spaces. The filetype doesn't seem to matter. Trivial strings e.g. `"this"\t"is"\t"a"\t"test"` reproduce the issue.

**Comment by martanne** [comment] 2020-01-28 12:29
Having merged #716 this particular case involving tabs should now work. However, the whole heuristic based approach is still very simplistic and fundamentally flawed. A proper solution would need to take the language semantics into account. See also #721, #668 and #714 for discussion/complaints about syntax highlighting.

**Closed by martanne** 2020-01-28 12:29 UTC
