### ISSUE TITLE
Some tabs collapse when the line is selected

### ISSUE THREAD

**Issue by mqudsi** [martanne/vis#734] opened 2018-09-17 00:01 UTC
Sorry for the awkward issue title, but I'm not sure how else to describe the problem I'm facing.

Here's an asciinema of the bug:
https://asciinema.org/a/20wjrcSX4fpeueSiSpLkkn8UF

Basically some lines with a leading tab have the tab collapsed when the cursor (in normal mode) is placed on that tab.

**Comment by rnpnr** [comment] 2023-06-07 03:19
Closing since we have no way to reproduce and no way of even seeing what the problem is. Feel free to reopen with more info.

**Closed by rnpnr** 2023-06-07 03:19 UTC
