### ISSUE TITLE
Poor performance on large $COLUMNS

### ISSUE THREAD

**Issue by raedwulf** [martanne/vis#71] opened 2015-09-14 05:54 UTC
I have quite a high resolution and sometimes my terminal width has COLUMNS > 200.

vis slows down drastically and chews up a lot of CPU... it seems that it doesn't scale well with the length of lines (even if they don't contain text)?

**Comment by martanne** [comment] 2015-09-14 13:19
While vis's core text handling data structures are designed to handle arbitrary input files (in particular large ones) well, the editor display frontend is currently not optimized at all. Part of it is a deliberate design decision to keep the code (relatively) simple. Currently no state is kept between redraws, we assume the underlying curses library performs double buffering and therefore reduces terminal output. In particular syntax highlighting is always recalculated upon redrawing, which potentially involves a lot of regex matching (likely the reason for the high CPU load). This is further amplified by the fact that with the introduction of multiple cursor support, every cursor movement will cause a full redraw (even if there exists only 1 cursor).

Having said that so far I assumed modern system would be fast enough to cope with it. Except for the few times I used 20+ cursors to edit [config.def.h](https://github.com/martanne/vis/blob/master/config.def.h) it was smooth enough on my 5+ year old laptop ...

Maybe other can chime in with their experience?

Could you provide some more information regarding your setup?
* do you have syntax highlighting enabled? which language?
* on what kind of file did you experience the poor performance?
* what libc or even better what kind of regex implementation do you use?
* a `gprof` or similar profile would be nice ...

**Comment by raedwulf** [comment] 2015-09-15 09:47
I tried a different C file and the performance was acceptable! So it seems that I hit a pathological case with: https://github.com/LemonBoy/bar/blob/master/lemonbar.c

I'll investigate a bit further if I have time...

**Comment by trengrj** [comment] 2015-09-15 10:22
I managed to get vis using 100% of cpu purely by scrolling down (holding down j)..

I'm using arch linux (glibc 2.22-3) with latest git vis running on xterm. File is config.def.h with default syntax highlighting.

`gprof` output

```
Flat profile:

Each sample counts as 0.01 seconds.
  %   cumulative   self              self     total           
 time   seconds   seconds    calls  ms/call  ms/call  name    
 91.31      0.21     0.21     1190     0.18     0.18  view_draw
  8.70      0.23     0.02     1186     0.02     0.02  ui_window_draw_text
  0.00      0.23     0.00   151392     0.00     0.00  text_iterator_valid
  0.00      0.23     0.00    93870     0.00     0.00  text_iterator_byte_next
  0.00      0.23     0.00    35839     0.00     0.00  text_iterator_byte_get
  0.00      0.23     0.00    35757     0.00     0.00  keyvalid
  0.00      0.23     0.00    34675     0.00     0.00  keymatch
  0.00      0.23     0.00    14079     0.00     0.00  text_iterator_byte_prev
  0.00      0.23     0.00     5374     0.00     0.00  piece_get_extern
  0.00      0.23     0.00     5001     0.00     0.00  text_iterator_init
  0.00      0.23     0.00     3815     0.00     0.00  text_iterator_get
  0.00      0.23     0.00     2770     0.00     0.00  view_coord_get
```

**Comment by raedwulf** [comment] 2015-09-15 11:22
I've just tried it with glibc and musl (without taking any particular numbers).  It runs smoothly with musl.  I suspect this might be to do with glibc's regex implementation being magnitudes slower.

**Comment by martanne** [comment] 2015-09-17 10:39
> I managed to get vis using 100% of cpu purely by scrolling down (holding down j)..

Yes this is kind of a known problem, you are not supposed to do that in a typical workflow. Use <kbd>Page-Down</kbd> if you have to. An easier way to reproduce this is to do something like `1000j` which will basically lock up the whole editor. The problem is that for such cases `view_draw` is currently called much too frequently.

> I've just tried it with glibc and musl (without taking any particular numbers). It runs smoothly with musl. I suspect this might be to do with glibc's regex implementation being magnitudes slower.

Yes this is what I was suspecting. Eventually vis should probably have its [own internal regex engine](https://github.com/martanne/vis#efficient-search-and-replace) using the same technique as the musl/TRE one.

**Comment by martanne** [comment] 2015-10-19 09:35
It would be highly appreciated if some of you who noticed these performance issues during normal usage could try out the [lua](https://github.com/martanne/vis/tree/lua) branch and report back how performance is there.

**Comment by martanne** [comment] 2015-11-02 16:21
I'm closing this because in the future syntax highlighting will be realized based on LPeg (see #81).

If you encounter performance issues on the [lua branch](https://github.com/martanne/vis/tree/lua) then please report them!

**Closed by martanne** 2015-11-02 16:21 UTC

**Comment by TieDyedDevil** [comment] 2015-11-02 19:06
FWIW, I've been using the lua branch for all of my editing for nearly two weeks.

WIth the master branch I did notice syntax highlighting performance issues, not with long lines but with C++ files in general. Scrolling line-by-line exhibited noticeable pauses.

With the lua branch, I no longer see any delays when scrolling by-line.
