### ISSUE TITLE
./configure: cannot find liblua

### ISSUE THREAD

**Issue by maskedbyte** [martanne/vis#642] opened 2017-12-09 21:19 UTC
OS: Gentoo Linux 4.12.12
Lua version: 5.2.3

I can't configure vis with Lua support.

`./configure --enable-lua`
```
checking for C compiler... cc     
checking whether C compiler works... yes
checking whether compiler accepts -Werror=unknown-warning-option... no
checking whether compiler accepts -Werror=unused-command-line-argument... no
checking whether linker accepts -Werror=unknown-warning-option... no        
checking whether linker accepts -Werror=unused-command-line-argument... no
checking whether compiler accepts -pipe... yes                            
checking whether compiler accepts -Os... yes  
checking whether compiler accepts -ffunction-sections... yes
checking whether compiler accepts -fdata-sections... yes    
checking whether linker accepts -Wl,--gc-sections... yes
checking whether compiler accepts -fPIE... yes          
checking whether compiler accepts -fstack-protector-all... yes
checking whether linker accepts -Wl,-z,now... yes             
checking whether linker accepts -Wl,-z,relro... yes
checking whether linker accepts -pie... yes        
creating config.mk... done                 
checking for pkg-config... yes
checking for libcurses...     
 checking for ncursesw... yes
checking for libtermkey... yes
checking for libtre... no     
checking for liblua >= 5.2 ...
 checking for lua... no       
 checking for lua5.3... no
 checking for lua5.2... no
 checking for lua-5.3... no
 checking for lua-5.2... no
 checking for lua53... no  
 checking for lua52... no
./configure: cannot find liblua
```
I've tried `PKG_CONFIG_PATH=/usr/lib` and `PKG_CONFIG_PATH=/usr/bin`. No effect.

`qlist lua`
```
...
/usr/include/lua5.2/lauxlib.h
/usr/include/lua5.2/lua.h
/usr/include/lua5.2/luaconf.h
/usr/include/lua5.2/lua.hpp
/usr/include/lua5.2/lualib.h
/usr/lib64/liblua5.2.la
/usr/lib64/liblua5.2.so.0.0.0
/usr/lib64/liblua5.2.a
/usr/lib64/pkgconfig/lua5.2.pc
/usr/lib64/liblua5.2.so.0
/usr/lib64/liblua5.2.so
/usr/bin/lua5.2
/usr/bin/luac5.2
...
```

```
> whereis lua
lua: /usr/bin/lua /usr/bin/lua5.2 /usr/lib64/lua /bin/lua /usr/include/lua5.2 /usr/share/lua
> ls -l /bin | grep lua
lrwxrwxrwx 1 root root      12 Dec  9 14:11 lua -> /usr/bin/lua
> ls -l /usr/bin | grep lua
lrwxrwxrwx   1 root root         15 Dec  9 15:00 lua -> /usr/bin/lua5.2
lrwxrwxrwx   1 root root          3 Dec  5 22:07 lua51 -> lua
lrwxrwxrwx   1 root root         15 Dec  9 15:00 lua52 -> /usr/bin/lua5.2
-rwxr-xr-x   1 root root      14600 Dec  9 15:00 lua5.2
-rwxr-xr-x   1 root root     129232 Dec  9 15:00 luac5.2
lrwxrwxrwx   1 root root         12 Dec  6 20:04 luajit -> luajit-2.0.4
-rwxr-xr-x   1 root root     449080 Dec  6 20:04 luajit-2.0.4
-rwxr-xr-x   1 root root     272128 Dec  5 22:08 luakit
lrwxrwxrwx   1 root root         12 Dec  6 16:43 luarocks -> luarocks-5.1
-rwxr-xr-x   1 root root        850 Dec  6 16:43 luarocks-5.1
lrwxrwxrwx   1 root root         18 Dec  6 16:43 luarocks-admin -> luarocks-admin-5.1
-rwxr-xr-x   1 root root        481 Dec  6 16:43 luarocks-admin-5.1
```

Weirdly, `libtermkey.so` and `libcurses.so` are also in `/usr/lib64` and it finds them, just not Lua.

**Comment by martanne** [comment] 2017-12-09 23:15
> /usr/lib64/pkgconfig/lua5.2.pc

Based on that I would try `PKG_CONFIG_PATH=/usr/lib64/pkgconfig` you can also try to manually tweak the {C,LD}FLAGS e.g. `CFLAGS=-I/usr/include/lua5.2`.

**Comment by maskedbyte** [comment] 2017-12-10 01:28
>`PKG_CONFIG_PATH=/usr/lib64/pkgconfig`
No effect.
>`CFLAGS=-I/usr/include/lua5.2`
Would I still configure after that, or just set the environment variable then `make`?

**Comment by maskedbyte** [comment] 2017-12-11 00:37
Make was ignoring the CFLAGS environment variable. I had to manually add the Lua include directory to the very long compile command (before I did that it said could not find lua.h when I forcibly enabled Lua in the mNow it akefile). Now it's saying this.
```
./util.h:28:14: error: static declaration of 'memrchr' follows non-static declaration
static void *memrchr(const void *m, int c, size_t n)                                      
             ^                        
/usr/include/string.h:118:14: note: previous declaration is here                                                                            
extern void *memrchr (const void *__s, int __c, size_t __n)     
```

**Comment by lanodan** [comment] 2017-12-17 01:08
Well here is my setup that have worked for quite a long time now, are you using eselect-lua and dev-lang/lua:5.2 from the lua overlay?
```terminal
$ eselect lua list
  [1]   5.1
  [2]   5.2 *
  [3]   jit-2.0.4
$ pkg-config -libs lua
-llua5.2 -lm
$ pkg-config -libs lua5.2
-llua5.2 -lm
$ pkg-config -libs lua5.1
-llua -lm
$ equery w dev-lang/lua:5.2
/var/lib/layman/lua/dev-lang/lua/lua-5.2.4.ebuild
$ equery w vis
/var/lib/layman/lanodanOverlay/app-editors/vis/vis-0.4.ebuild
```

**Comment by lanodan** [comment] 2017-12-17 01:57
Also I managed to reproduce with (guessed on your on your lua version):
* app-eselect/eselect-lua-1::gentoo
* dev-libs/unibilium-1.1.4::gentoo
* dev-libs/libtermkey-0.19::gentoo

The ``dev-lang/lua-5.2.3-r2::gentoo`` ebuild is masked and unmaintained since Aug 2016. Please try with the lua overlay (with is supported as it’s a Gentoo Project overlay).

**Comment by martanne** [comment] 2017-12-21 21:19
`./configure CFLAGS=-I/usr/include/lua5.2 && make` is one way to add specific C flags. Also as a last resort it should be fairly easy to tweak the generated `config.mk` file.

I'm closing this as it seems to be a distribution issue (your `pkg-config` files aren't set up correctly?).

**Closed by martanne** 2017-12-21 21:19 UTC
