### ISSUE TITLE
Cursor position issues

### ISSUE THREAD

**Issue by rychipman** [martanne/vis#42] opened 2015-04-14 20:08 UTC
When changing from insert to normal mode, the cursor doesn't move back one column as it does in vi and vim. Not sure if this is an oversight or a conscious decision.

Also, the cursor's column position gets decreased when it enters a row with fewer columns than the previous row. So instead of the cursor displaying in column 5 for any rows with >= 5 columns and displaying in the last column for any shorter columns, entering into a row with, say, 3 columns will actually change the cursor's position.

**Comment by martanne** [comment] 2015-04-14 22:27
> When changing from insert to normal mode, the cursor doesn't move back one column as it does in vi and vim. Not sure if this is an oversight or a conscious decision.

I guess a combination of both. For which reasons would you prefer the vim behavior?

The other issue should hopefully be fixed (well at least for the simple non-wrapped case). And yes the cursor movement code is an ugly mess.

**Comment by rychipman** [comment] 2015-04-15 00:24
At least for me, it introduces some confusion about what exists at the end of a line. The cursor can move one column past the last character on the line, but that character is not a space. In fact, it is the newline character (which you can verify by deleting it). The exception to this is the end of the file, where that extra column can be accessed by the cursor but does not seem to represent a character at all.

**Comment by rychipman** [comment] 2015-06-11 14:26
Another somewhat-related issue (which I plan to address at some point) is that a redo leaves the cursor at the *start* position of the redone action, not at the *end* where it ought to be.

**Comment by martanne** [comment] 2015-07-28 11:43
In the latest commits I introduced support for multiple cursors/selections.

This will further complicate cursor positioning. For now it does not move the cursor upon undo/redo. In general this is all brand new and quite rough around the edges. For example selections are not merged if they overlap, thus causing sometimes unexpected outcomes. Also a few commands are probably not yet converted to deal with multiple cursors. I have a couple of ideas for further improvements but currently not enough time to pursue them.
 
For now the (somewhat arbitrary, suggestions welcome) recognized keybindings are, in normal mode:

    CTRL-J   create a new cursor on line below
    CTRL-K   create a new cursor on line above
    CTRL-P   remove least recently added cursor
    CTRL-N   select word the cursor is currently over, switch to visual mode
    CTRL-A   try to align all cursor on the same column
    ESC      if a selection is active, clear it.
             Otherwise dispose all but the primiary cursor.

In visual mode:

    CTRL-N   create new cursor and select next word matching current selection
    CTRL-X   clear (skip) current selection, but select next matching word
    CTRL-P   remove least recently added cursor
    CTRL-O   creates a new cursor at the start of every line covered by the current selection

Some testing would be appreciated. Comments and patches welcome!

**Comment by martanne** [comment] 2015-08-02 10:34
In the meantime `CTRL-O` in visual mode was superseded by `A` and `I` respectively. They create a new cursor and  place it at the start/end of every selected line.

Also `CTRL-J` is a synonym for ENTER. Not sure if this is the best choice. It certainly encourages the use of multiple cursors though ...

**Closed** 2015-11-02 18:48 UTC

**Comment by pickfire** [comment] 2016-08-06 09:07
It seems weird that vis cursor is able to float in the last character in the line.

![2016-08-06-165601_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/17455863/ca963c90-5bf7-11e6-85b5-156ca2daae3d.png)

Unlike vim and neovim:

![2016-08-06-165639_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/17455860/bf223742-5bf7-11e6-9b6a-2812a1e5e010.png)

By the way, how useful is ncurses here? It isn't supporting true color yet. (and vim doesn't depend on it)

**Comment by martanne** [comment] 2016-08-06 11:28
Yes newlines are addressable in vis, for now this is [intended behavior](https://github.com/martanne/vis/pull/54#issuecomment-215033679).

**Comment by pickfire** [comment] 2016-08-06 12:53
Oh, I think I need some time to be more comfortable with the extra newline behaviour before I might think about getting vis to replace neovim.

Vis seems to have nice syntax for man pages but I can't do `{` or `[[` for navigation in man pages, is that intended too?

**Comment by pickfire** [comment] 2016-12-13 16:28
@martanne Is there any workaround for ignoring the extra newline in non-empty lines? It really seems annoying for me and it is the main reason I am not switching to vis.
