### ISSUE TITLE
incorrect colors in st terminal

### ISSUE THREAD

**Issue by pshevtsov** [martanne/vis#549] opened 2017-05-12 21:38 UTC
I'm not sure, probably that's the bug with `st`, but `vis` with default (solarized) color scheme displays incorrect background color:
![urxvt-vs-st](https://cloud.githubusercontent.com/assets/290451/26017847/663e9162-3774-11e7-859e-bc9550b93b05.png)
(`urxvt` is on the left and `st` is on the right)

**Comment by xcko** [comment] 2017-05-16 07:27
I can confirm this bug as well.

**Comment by martanne** [comment] 2017-05-16 07:52
The reason for this is that the [default st terminfo description](http://git.suckless.org/st/tree/st.info#n194) does not advertise the color change capabilities. This is fixed in the [terminfo description shipped with ncurses](http://invisible-island.net/ncurses/terminfo.ti.html#tic-st-256color) (via the [`xterm+256color` reference](http://invisible-island.net/ncurses/terminfo.ti.html#tic-xterm_256color).

Applying the [following patch to st](http://sprunge.us/ThjF) and (re-)installing the terminfo description using `tic -sx st.info` should fix it.

```
From fccc4962491ccb159d20836147ccb7c2cd96aef1 Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?Marc=20Andr=C3=A9=20Tanner?= <mat@brain-dump.org>
Date: Mon, 15 May 2017 12:45:41 +0200
Subject: [PATCH] Add color change terminfo capabilities

---
 st.info | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/st.info b/st.info
index 0b928af..4d77eae 100644
--- a/st.info
+++ b/st.info
@@ -193,9 +193,12 @@ st| simpleterm,
 
 st-256color| simpleterm with 256 colors,
 	use=st,
+	ccc,
 	colors#256,
+	oc=\E]104\007,
 	pairs#32767,
 #	Nicked from xterm-256color
+	initc=\E]4;%p1%d;rgb\:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
 	setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
 	setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
 
-- 
1.9.1
```

**Closed** 2017-05-16 09:14 UTC

**Comment by martanne** [comment] 2017-06-04 16:12
The above patch has been [committed to the st repository](http://git.suckless.org/st/commit/?id=b331da550b290d54592b7ba11242c92f5a303a48).
