### ISSUE TITLE
How to avoid to open same file more than one time?

### ISSUE THREAD

**Issue by Disonantemus** [martanne/vis#1141] opened 2023-10-04 20:23 UTC
I use _tmux_ frequently, sometimes with several **vis** instances, sometimes I did open same file 2 times. I would prefer at least a warning to avoid open same file again, how can I do that?

---

OS: Arch Linux x86_64
Kernel: 6.1.52-1-lts
Shell: fish 3.6.1
Resolution: 1920x1080
WM: dwm
Terminal: tmux
CPU: Intel i7-4790 (8) @ 3.600GHz
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590

**Comment by rnpnr** [comment] 2023-10-10 20:40
duplicate of #968

**Comment by mcepl** [comment] 2023-12-02 21:25
Again, why is this ticket not closed?

**Closed** 2023-12-02 22:45 UTC
Labels: meta:duplicate
