### ISSUE TITLE
Search after invalid chars

### ISSUE THREAD

**Issue by jk411** [martanne/vis#1142] opened 2023-10-07 14:28 UTC
echo 61 61 b6 62 62 0a | xxd -p -r >file
vis file

Search
"/b"
doesn't work,
characters after invalid char 0xb6 can't be found if cursor is before it

Last version of vis
compiled from sources
on Alpine Linux (musl)

**Comment by rnpnr** [comment] 2023-10-11 00:19
duplicate of #1064

**Comment by mcepl** [comment] 2023-12-02 21:24
> duplicate of #1064

So, why is this ticket not closed?

**Closed** 2023-12-02 22:44 UTC
Labels: meta:duplicate, core:text
